site_name: OriGen Documentation
site_description: Deterministic Workflow Planning and Portable Execution
site_url: https://origen-hub.github.io/origen-core-public
repo_url: https://github.com/origen-hub/origen-core-public
repo_name: origen-core-public

docs_dir: docs/public

plugins:
  - autorefs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy

# Optional (makes the docs nicer)
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - footnotes
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Primer: overview/origen-primer.md
  - Value Statement: overview/value.md
  - Top-Level Overview: architecture/00-top-level.md
  - About: pages/about.md

  - Community:
      - Code of Conduct: pages/CODE_OF_CONDUCT.md
      - Contributing: pages/CONTRIBUTING.md
      - Security Policy: pages/SECURITY.md
      - License: pages/LICENSE.md
      - Notice: pages/NOTICE.md
      - Copyright: pages/COPYRIGHT.md
